baseURL = 'https://boreec.github.io/'
languageCode = 'en-us'
title = 'boreec.github.io'
theme = 'archie'

[params]
mode="light"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/boreec"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/Boree_c"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/cyprien-boree/"

[[menu.main]]
name = "home"
url = "/"
weight = 1

[[menu.main]]
name = "resume"
url = "/resume"
weight = 2
